config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  resources :about
  resources :details
  resources :gallery
  resources :contact

  get 'locations', to: 'contact#locations'
  get 'image_path', to: 'home#cover_image'
  get '/vendors', to: 'vendor#index', as: 'vendors'
  post 'contact_request', to: 'contact#request_info'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @details = Detail.all
  end

  def create
    detail = Detail.create(detail_params)
    render json: detail
  end

  def destroy
    Detail.find(params[:id]).destroy
    @details = Detail.all
    render 'index'
  end

  private

  def detail_params
    params.require(:detail).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :nav_class, :admin

  def nav_class
    navs = %w(home about gallery contact vendor)
    if navs.include?(params[:controller])
      @nav_class = "#{params[:controller]}-nav"
    else
      @nav_class = 'default-nav'
    end
  end

  def admin
    @admin = admin_signed_in?
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def locations
    shop = Location.find_by(loc_type: 'shop')
    office = Location.find_by(loc_type: 'office')
    render json: { shop: shop, office: office }
  end

  def request_info
    contact = params[:contact]
    begin
      ContactMailer.contact(contact[:name], contact[:email], contact[:content]).deliver
      flash[:notice] = "Your message has been sent"
    rescue => e
      logger.error e.message
      flash[:error] = "Something went wrong please try again"
    end
    redirect_to contact_index_path
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @details = Detail.all
  end

  def create
    detail = Detail.create(detail_params)
    render json: detail
  end

  def destroy
    Detail.find(params[:id]).destroy
    @details = Detail.all
    render 'index'
  end

  private

  def detail_params
    params.require(:detail).permit(:name)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
    @posts = Instagram.user_recent_media
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def cover_image
    render json: { path: ActionController::Base.helpers.asset_path("cover-compressor.png") }
  end
end

app/controllers/vendor_controller.rb
class VendorController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then
        'info'
      when :error then
        'error'
      when :alert then
        'warning'
    end
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/views/about/index.html.haml
.row.white
  .col.s12.m6
    .about-img.hide-on-med-and-down
  .col.s12.m6
    %img.about-logo{src: image_path('SpeedShop_Logo_4.png')}
  .col.s12.m12.white
    .about-content.white.container
      %p Ryan DeCol born 1974 raised in Copperton and Sandy Utah. My grandfather put the love of cars into me at a young age by teaching me how to work on them. Growing up we had a 67' Chevy II that my mother drove, man I loved that car.  As I grew up I was always tearing my bike apart and modifying it along with model cars and every other toy I ever got along the way. Both of my step fathers were very much into cars, trucks and race cars which furthered my love and ability in working on and customizing big boy toys.
      %p I joined the Marine Corps in 1992 as soon as I graduated high school and of course my first job duty was to be a mechanic.  I served my country proudly and left the Corps Honorably and moved on.  Over the years I have built and worked on boats, heavy trucks, armored heavy vehicles, and every car and truck imaginable. My passion lies in building, repairing and customizing cars, trucks and motorcycles.  Through these great growing years I have done a lot along the way with a ton of great people that I respect and thank for all the knowledge and opportunities that have been given to me and earned by myself.

      %p Now the big venture begins! Which leads us here to;
      %br
      %br
      %h3.center DeCol's Speed Shop
.social-links.white-text.col.s12.m6.center
  %a.white-text.large-font{href: 'tel:8018333272'} (801) 833-3272
  %a.white-text{href: 'https://www.instagram.com/decols_speed_shop/', target: '_blank'}
    = fa_icon 'instagram 3x'
  %a.white-text{href: 'https://www.facebook.com/Decolsspeedshop/', target: '_blank'}
    = fa_icon 'facebook 3x'
  %a.white-text{href: 'https://www.twitter.com/decolryan/', target: '_blank'}
    = fa_icon 'twitter 3x'

app/views/contact/index.html.haml
%h3.center.white-text Contact
= react_component 'Locations'
.row
  #hours.col.s12.m4
    .card.grey.darken-3.z-depth-4
      .card-content.white-text
        %ul.collection.with-header
          %li.collection-header.grey
            %h4.center Hours
          %li.grey.collection-item
            Mon: 8:AM - 5:PM
          %li.grey.collection-item
            Tue: 8:AM - 5:PM
          %li.grey.collection-item
            Wed: 8:AM - 5:PM
          %li.grey.collection-item
            Thu: 8:AM - 5:PM
          %li.grey.collection-item
            Fri: 8:AM - 5:PM
          %li.grey.collection-item
            Sat: By Appointment
          %li.grey.collection-item
            Sun: Closed
  #contact.col.s12.m8
    %h5.white-text.center Questions / Comments
    = form_for :contact, url: 'contact_request' do |f|
      = f.text_field :name, { class: 'white-text', required: true, placeholder: 'Name' }
      = f.email_field :email, { class: 'white-text', required: true, placeholder: 'Email' }
      = f.text_area :content, { class: 'one-hundred-percent white-text', required: true, rows: 10 }
      = f.submit :submit, { class: 'btn black' }

app/views/gallery/index.html.haml
%h3.center Gallery
.center
= react_component 'InstagramContainer', { posts: @posts }

app/views/home/index.html.haml
#main.first-panel-content.row
  .home-motto.valign-wrapper
    %img.motto.valign.center{src: image_path('SpeedShop_Logo_4.png')}
  .row
    .col.s12.m6.hide-on-small-only
      %a.right{href: '#about'}
        = fa_icon('chevron-down inverse 3x')
    .social-links.col.s12.m6.center
      %a.white-text.large-font.phone.white-text{href: 'tel:8018333272'} (801) 833-3272
      %a.green-icon{href: 'https://www.instagram.com/decols_speed_shop/', target: '_blank'}
        = fa_icon 'instagram 3x'
      %a.green-icon{href: 'https://www.facebook.com/Decolsspeedshop/', target: '_blank'}
        = fa_icon 'facebook 3x'
      %a.green-icon{href: 'https://www.twitter.com/decolryan/', target: '_blank'}
        = fa_icon 'twitter 3x'
#about.intro.row
  .col.s12
    %h1.center WHAT WE DO
    = react_component 'About', { admin: @admin }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="Nl91AqzIe2yJPn3R_L9wvrCgn88xz3zNJs5I67lmU_s" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Decols</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <main>
    <%= render partial: 'shared/bflash' %>
    <%= render partial: 'shared/top_nav' %>
    <%= yield %>
    <footer class="page-footer grey darken-2">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <p class="grey-text text-lighten-4">Handcrafted In Salt Lake City By: <a href="http://www.cottonwoodcoding.com" target="_blank">Cottonwood Coding</a></p>
          </div>
        </div>
      </div>
      <div class="footer-copyright grey darken-2">
        <div class="container">
          © 2016 Decols Speed Shop
        </div>
      </div>
    </footer>
  </main>
</body>
</html>

app/views/shared/_bflash.haml
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    %div.text-center{:class => "alert #{"alert-#{flash_class(level)}"} hidden-xs"}
      = content_tag :strong, flash[level]

app/views/shared/_top_nav.haml
.navbar-fixed
  %nav#top-nav{class: @nav_class}
    .nav-wrapper
      %a.brand-logo{href: '/'}
        %img.responsive-img.nav-logo.logo{src: asset_path('speed_shop_logo_long.png')}
      %a.button-collapse{"data-activates" => "mobile-demo", href: "#"}
        = fa_icon 'bars'
      %ul.right.hide-on-med-and-down
        %li
          = link_to "Home", "/"
        %li
          = link_to "About", about_index_path
        %li
          = link_to "Gallery", gallery_index_path
        %li
          = link_to "Contact", contact_index_path
        - if admin_signed_in?
          %li
            = link_to "Sign Out", destroy_admin_session_path, method: :delete
        %li
          = link_to "Vendors", vendors_path
      %ul#mobile-demo.side-nav
        %li
          = link_to "Home", "/"
        %li
          = link_to "About", about_index_path
        %li
          = link_to "Gallery", gallery_index_path
        %li
          = link_to "Vendors", vendors_path
        %li
          = link_to "Contact", contact_index_path
        - if admin_signed_in?
          %li
            = link_to "Sign Out", destroy_admin_session_path, method: :delete